// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// second one

// import "./globals.css";

// export const metadata = {
//   title: "My App",
//   description: "Using Tailwind with Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-white text-gray-900 antialiased">
//         {children}
//       </body>
//     </html>
//   );
// }


// import "./globals.css";
// import Header from "../../components/layouts/header";
// import Footer from "../../components/layouts/footer";
// import MobileHeader from "../../components/layouts/MobileHeader";

// export const metadata = {
//   title: "My App",
//   description: "Next.js App with Layout",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen flex flex-col">
//         <Header />
//         <MobileHeader />
//         <main className="flex-grow">{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }






import Header from "../../components/layouts/header";
import Footer from "../../components/layouts/footer";
import MobileHeader from "../../components/layouts/MobileHeader";

export const metadata = {
  title: "My App",
  description: "Next.js App with Layout",
};

export default function SiteLayout({ children }) {
  return (
    <>
      <Header />
      <MobileHeader />
      <main className="flex-grow">{children}</main>
      <Footer />
    </>
  );
}
